# Use postgres/example user/password credentials
version: '3.1'

services:
  service:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devops
    ports:
      - "5432:5432"

volumes:
  db_data: